### ISSUE TITLE
updte IMMEDIATELY

### ISSUE THREAD

**Issue by Vendicated** [MeguminSama/JSX-Reconstructor#2]
:trollface: :shipit: 🚎

**Comment by Vendicated** [comment]
why did you add the wontfix label >:(

**Comment by MeguminSama** [comment]
skill issue + ratio bozo

**Comment by Vendicated** [comment]
i hope you explode

**Comment by sneksnake** [comment]
Update !!!!! or u will explod

**Comment by MeguminSama** [comment]
I EXPLOD

**Comment by MeguminSama** [comment]
HORROR

**Comment by sneksnake** [comment]
NOOOOO :!!!!!!!!!!!!!!!

**Comment by MeguminSama** [comment]
oh wait this was actually completed :trollface: https://github.com/MeguminSama/JSX-Reconstructor/commit/d3914f0bcd61753bb9c21d35bdfdc80c212c3ef0
